# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cisuba' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cisuba
pod "ESTabBarController-swift"
pod 'pop', '~> 1.0'
pod 'ImageSlideshow', '~> 1.2'
pod "ImageSlideshow/Alamofire"
pod 'DropDown'
pod 'Gloss', '~> 1.2'

  target 'CisubaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CisubaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
